metadata:
  name: Yonisfy
  short_name: Yonisfy
  description: mohammed elzanaty
  language: en
  url: 'https://mohammedelzanaty.github.io/yonisfy/'
  pathPrefix: /yonisfy
  gaTrackingId: null
  favicon: /assets/favicon.ico
  themeColor: '#0066cc'
header:
  enabled: true
  logo: /assets/logo.png
  links: []
sidebar:
  groups:
      - order: 1
        path: "/components"
        title: ":hammer_and_wrench: Components"
      - order: 2
        path: "/udacity"
        title: "‚òïÔ∏è Udacity"
      - order: 3
        path: "/interview-questions"
        title: ":rocket: Interviews"
      - order: 4
        path: "/my-path-to-learn"
        title: ":railway_track: Road Map"
      - order: 5
        path: "/info"
        title: "üá™üá¨ Info"
  ignoreIndex: false
  forcedNavOrder: []
  expanded: []
  links: []
  poweredBy: {}
  enabled: true
pwa:
  enabled: true
  manifest:
    icon: /assets/logo-dark.png
    display: minimal-ui
    crossOrigin: anonymous
social:
  github: 'https://github.com/mohammedelzanaty'
  linkedin: 'https://www.linkedin.com/in/mohammedelzanaty129/'
  mail: mohammedelzanaty129@gmail.com
  twitter: 'https://twitter.com/mohammdelzanaty'
  youtube: 'https://www.youtube.com/c/mohammedelzanatyacademy'
features:
  editOnRepo:
    editable: true
    location: 'https://github.com/mohammedelzanaty/yonisfy'
    type: github
  rss:
    enabled: false
    showIcon: true
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
  scrollTop: true
  search:
    enabled: true
    algoliaAppId: null
    algoliaSearchKey: null
    algoliaAdminKey: null
    engine: localsearch
    localSearchEngine: balance
    placeholder: Search here...
    pagination:
      enabled: true
      totalPages: 10
      showNext: true
      showPrevious: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
  previousNext:
    enabled: true
    arrowKeyNavigation: true