# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'yonisfy':
  name: yonisfy
  long_name: yonisfy
  description: mohammed elzanaty
